apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: vijaylearning/employee-backend:20250726232304  # Change if using Docker Hub/Harbor
          ports:
            - containerPort: 8080