apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cd2a4103-ed80-4ee8-8de6-770cf32b85de"
    keyvaultName: "vijay-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: POSTGRESPASSWORD
          objectType: secret
    tenantId: 51a90b13-a1c4-4b39-931e-af430ea3186e
  secretObjects:
    - secretName: db-password-k8s
      type: Opaque
      data:
        - objectName: POSTGRESPASSWORD
          key: POSTGRESPASSWORD