apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "fffe0b01-a259-436e-802a-b8d7bcf9e7e6"
    keyvaultName: "vijay-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: POSTGRESPASSWORD
          objectType: secret
    tenantId: 51a90b13-a1c4-4b39-931e-af430ea3186e
  secretObjects:
    - secretName: db-password-k8s
      type: Opaque
      data:
        - objectName: POSTGRESPASSWORD
          key: POSTGRESPASSWORD